"""
orchestrator.py - Main orchestrator for the AI Employee

The orchestrator:
1. Monitors the Needs_Action folder for new action files
2. Triggers Claude Code to process pending items
3. Updates the Dashboard.md with current status
4. Manages the overall workflow

Usage:
    python orchestrator.py /path/to/AI_Employee_Vault
"""

import sys
import subprocess
import logging
from pathlib import Path
from datetime import datetime
from typing import Optional


class Orchestrator:
    """
    Main orchestrator for the AI Employee system.
    
    Coordinates between watchers, Claude Code, and the vault.
    """
    
    def __init__(self, vault_path: str, check_interval: int = 30):
        """
        Initialize the orchestrator.
        
        Args:
            vault_path: Path to the Obsidian vault root
            check_interval: How often to check for pending items (in seconds)
        """
        self.vault_path = Path(vault_path)
        self.check_interval = check_interval
        
        # Key folders
        self.needs_action = self.vault_path / 'Needs_Action'
        self.pending_approval = self.vault_path / 'Pending_Approval'
        self.approved = self.vault_path / 'Approved'
        self.plans = self.vault_path / 'Plans'
        self.done = self.vault_path / 'Done'
        self.logs = self.vault_path / 'Logs'
        self.dashboard = self.vault_path / 'Dashboard.md'
        
        # Ensure directories exist
        for folder in [self.needs_action, self.pending_approval, self.approved, 
                       self.plans, self.done, self.logs]:
            folder.mkdir(parents=True, exist_ok=True)
        
        # Setup logging
        self._setup_logging()
        
        # Track processed files
        self.processed_files = set()
        
        # Claude Code state
        self.claude_process: Optional[subprocess.Popen] = None
    
    def _setup_logging(self):
        """Setup logging to file and console."""
        log_file = self.logs / f'orchestrator_{datetime.now().strftime("%Y-%m-%d")}.log'
        
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            handlers=[
                logging.FileHandler(log_file),
                logging.StreamHandler()
            ]
        )
        self.logger = logging.getLogger('Orchestrator')
    
    def check_needs_action(self) -> list:
        """
        Check the Needs_Action folder for unprocessed files.
        
        Returns:
            list: List of .md files waiting to be processed
        """
        if not self.needs_action.exists():
            return []
        
        pending_files = []
        for file_path in self.needs_action.glob('*.md'):
            if file_path.name not in self.processed_files:
                pending_files.append(file_path)
        
        return pending_files
    
    def check_approved(self) -> list:
        """
        Check the Approved folder for actions to execute.
        
        Returns:
            list: List of approved action files
        """
        if not self.approved.exists():
            return []
        
        approved_files = []
        for file_path in self.approved.glob('*.md'):
            if file_path.name not in self.processed_files:
                approved_files.append(file_path)
        
        return approved_files
    
    def trigger_qwen(self, prompt: str) -> bool:
        """
        Trigger Qwen Code to process items.
        
        Note: Qwen Code requires interactive mode. For batch processing,
        we write the prompt to a state file that can be processed manually.

        Args:
            prompt: The prompt to give Qwen Code

        Returns:
            bool: True if Qwen was triggered successfully
        """
        self.logger.info(f'Triggering Qwen Code with prompt: {prompt[:100]}...')

        try:
            # Change to vault directory
            original_dir = Path.cwd()
            import os
            os.chdir(self.vault_path)

            # Write prompt to a state file for manual Qwen invocation
            # This is the Bronze tier approach - user runs Qwen manually
            state_file = self.vault_path / '.qwen_pending.md'
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            
            state_content = f'''---
created: {timestamp}
status: pending
type: qwen_prompt
---

# Pending Qwen Code Task

Run the following command in this directory to process:

```bash
qwen
```

Then paste this prompt:

{prompt}

---
*Auto-generated by AI Employee Orchestrator*
'''
            state_file.write_text(state_content, encoding='utf-8')
            
            self.logger.info(f'Created pending task file: {state_file.name}')
            self.logger.info('To process: Run "qwen" in the vault directory')
            
            os.chdir(original_dir)
            return True
                
        except Exception as e:
            self.logger.error(f'Error triggering Qwen Code: {e}')
            return False
    
    def update_dashboard(self, pending_count: int, approved_count: int):
        """
        Update the Dashboard.md with current status.
        
        Args:
            pending_count: Number of items in Needs_Action
            approved_count: Number of items in Approved
        """
        if not self.dashboard.exists():
            self.logger.warning('Dashboard.md not found')
            return

        try:
            # Read with UTF-8 encoding to handle emoji characters
            content = self.dashboard.read_text(encoding='utf-8')

            # Update status line
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            content = content.replace(
                '**Last Activity**: --',
                f'**Last Activity**: {timestamp}'
            )

            # Update pending count
            content = content.replace(
                '**Pending Items**: 0',
                f'**Pending Items**: {pending_count}'
            )

            # Update metrics
            content = content.replace(
                'Tasks Completed Today | 0',
                f'Tasks Completed Today | {len(list(self.done.glob("*.md")))}'
            )

            content = content.replace(
                'Pending Approvals | 0',
                f'Pending Approvals | {approved_count}'
            )

            # Write with UTF-8 encoding to handle emoji characters
            self.dashboard.write_text(content, encoding='utf-8')
            self.logger.debug('Dashboard updated')

        except Exception as e:
            self.logger.error(f'Error updating dashboard: {e}')
    
    def process_pending_items(self):
        """Process all pending items in Needs_Action."""
        pending_files = self.check_needs_action()

        if not pending_files:
            self.logger.debug('No pending items to process')
            return

        self.logger.info(f'Found {len(pending_files)} pending item(s)')

        # Build prompt for Qwen
        file_list = '\n'.join([f'- {f.name}' for f in pending_files])
        prompt = f'''Process the following files in /Needs_Action:

{file_list}

For each file:
1. Read and understand what action is needed
2. Check Company_Handbook.md for rules and guidelines
3. Create a Plan.md file if multi-step action is required
4. Execute allowed actions directly
5. Create approval requests in /Pending_Approval for sensitive actions
6. Move completed items to /Done

Follow the Ralph Wiggum pattern - keep working until all items are processed.'''

        # Trigger Qwen
        success = self.trigger_qwen(prompt)

        if success:
            # Mark files as processed
            for file_path in pending_files:
                self.processed_files.add(file_path.name)
    
    def process_approved_items(self):
        """Process approved actions ready for execution."""
        approved_files = self.check_approved()

        if not approved_files:
            self.logger.debug('No approved items to process')
            return

        self.logger.info(f'Found {len(approved_files)} approved item(s)')

        # Build prompt for Qwen
        file_list = '\n'.join([f'- {f.name}' for f in approved_files])
        prompt = f'''Execute the following approved actions in /Approved:

{file_list}

For each file:
1. Read the approval request
2. Execute the approved action using appropriate MCP servers
3. Log the result
4. Move the file to /Done after completion

Report the results of each action.'''

        # Trigger Qwen
        success = self.trigger_qwen(prompt)

        if success:
            # Mark files as processed
            for file_path in approved_files:
                self.processed_files.add(file_path.name)
    
    def run(self):
        """
        Main run loop for the orchestrator.

        Continuously checks for pending and approved items,
        triggering Qwen Code as needed.
        """
        self.logger.info('=' * 50)
        self.logger.info('AI Employee Orchestrator Starting')
        self.logger.info(f'Vault: {self.vault_path}')
        self.logger.info(f'Check interval: {self.check_interval}s')
        self.logger.info('=' * 50)
        
        try:
            while True:
                # Check and process pending items
                self.process_pending_items()
                
                # Check and process approved items
                self.process_approved_items()
                
                # Update dashboard
                pending_count = len(self.check_needs_action())
                approved_count = len(self.check_approved())
                self.update_dashboard(pending_count, approved_count)
                
                # Wait before next check
                import time
                time.sleep(self.check_interval)
                
        except KeyboardInterrupt:
            self.logger.info('Orchestrator stopped by user')
        except Exception as e:
            self.logger.error(f'Fatal error: {e}')
            raise


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: python orchestrator.py <vault_path>")
        print("Example: python orchestrator.py ./AI_Employee_Vault")
        sys.exit(1)
    
    vault_path = sys.argv[1]
    
    if not Path(vault_path).exists():
        print(f"Error: Vault path does not exist: {vault_path}")
        sys.exit(1)
    
    orchestrator = Orchestrator(vault_path)
    orchestrator.run()


if __name__ == '__main__':
    main()
